CREATE TABLE IF NOT EXISTS `train_schema`.`trains` (
  `idtrains` INT(11) NOT NULL COMMENT '',
  `destpoint` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `time` TIME NULL DEFAULT NULL COMMENT '',
  `day` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idtrains`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8